### ISSUE TITLE
Cannot found with OpenTofu

### ISSUE THREAD

**Issue by back-2-95** [UpCloudLtd/terraform-provider-objsto#14]
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ upcloudltd/objsto: provider registry registry.opentofu.org does not have a
│ provider named registry.opentofu.org/upcloudltd/objsto

**Comment by kangasta** [comment]
Thanks for trying this already! We'll create a PR to the OpenTofu registry repository to get this included also there.

**Comment by kangasta** [comment]
Created the submission issue now: https://github.com/opentofu/registry/issues/1349

**Comment by back-2-95** [comment]
Thanks, now I can use the provider
