### ISSUE TITLE
Q: difference between objsto_bucket and upcloud_managed_object_storage_bucket ?

### ISSUE THREAD

**Issue by back-2-95** [UpCloudLtd/terraform-provider-objsto#15]
Moving into testing this new provider.

Just got confused about `objsto_bucket` resource in this Provider and `upcloud_managed_object_storage_bucket` resource in UpCloud Provider?

**Comment by kangasta** [comment]
All resources in this provider use S3 API endpoint to manage the object storage where as the `upcloud_managed_object_storage_bucket` (and other `upcloud_managed_object_storage_` resources) use UpCloud API. The behaviour between these can be slightly different: For example, the UpCloud API allows deleting non-empty buckets, but S3 API does not.

This could be clarified also in the documentation of `upcloud_managed_object_storage_bucket`.

**Comment by back-2-95** [comment]
thx, as we need to use lifecycle things and policies, maybe it would be reasonal to use `objsto_bucket` to create bucket and additional things related to it.
